name: csrd_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Sanity Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
#          flutter-version: '3.19.6'
      - name: Create Firebase options
        run: \cp -f test/firebase_options.dart lib/
      - name: Get dependencies
        run: flutter pub get
      - name: Test project
        run: flutter test
      - name: Build project
        run: flutter build web
